# tests/contracts/agent_registry_contract.py
#
# RESPONSIBILITY
#   Conformance suite for AgentRegistry. Verifies the load/reload/
#   deregister/get/list contract independently of the implementation.
#
# WHAT TO IMPLEMENT
#   - class AgentRegistryContract:
#       registry_factory: ClassVar[Callable[[], AgentRegistry]]
#       valid_agent_path:  ClassVar[Path]   (path to a valid agent-xx.yaml)
#       alt_agent_path:    ClassVar[Path]   (same agent_id, different content)
#
#       def test_load_registers_agent(self): ...
#       def test_load_idempotent_on_identical_content(self): ...
#       def test_load_raises_conflict_on_different_content(self): ...
#       def test_reload_replaces_existing(self): ...
#       def test_reload_raises_on_unknown_agent(self): ...
#       def test_reload_keeps_old_on_invalid_file(self): ...
#       def test_deregister_removes_agent(self): ...
#       def test_deregister_raises_on_unknown(self): ...
#       def test_get_returns_registered_agent(self): ...
#       def test_get_raises_on_unknown(self): ...
#       def test_list_returns_all_registered(self): ...
#
#       def test_concurrent_get_is_safe(self):
#           """50 threads call get() simultaneously on a registered agent.
#           No exceptions, all return the correct AgentConfig."""
